controllers_prod:
    resource: ../src/Application/Controller/
    type: annotation

test_controllers:
    resource: ../src/SeparateCategory/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
